kind: pipeline
type: docker
name: arm64

platform:
  arch: arm64

steps:
  - name: docker-arm64
    platform:
    image: plugins/docker
    settings:
      username: danacr
      password:
        from_secret: docker_password
      repo: danacr/drone-pod
      tags: arm64-latest
  - name: manifest
    image: plugins/manifest
    settings:
      username: danacr
      password:
        from_secret: docker_password
      target: danacr/drone-pod:latest
      template: danacr/drone-pod:arm64-latest
      platforms:
        - linux/arm64
---
kind: pipeline
type: docker
name: amd64

platform:
  arch: amd64

steps:
  - name: docker-amd64
    image: plugins/docker
    settings:
      username: danacr
      password:
        from_secret: docker_password
      repo: danacr/drone-pod
      tags: amd64-latest
  - name: manifest
    image: plugins/manifest
    settings:
      username: danacr
      password:
        from_secret: docker_password
      target: danacr/drone-pod:latest
      template: danacr/drone-pod:amd64-latest
      platforms:
        - linux/amd64
